import { FoodItem } from "@/interface/types";

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: "fd_zZyWJnVH2azN",
    name: "Made by Lukas, Fresh Veggie Burers by Chekit",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.02,
      sodium: 255,
      calcium: 38,
      protein: 2.83,
      calories: 113,
      total_fat: 2.83,
      vitamin_c: 2.3,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 2.83,
      vitamin_a_iu: 2830,
      carbohydrates: 18.9,
      dietary_fiber: 3.8,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 106,
      },
      metric: {
        unit: "g",
        quantity: 106,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zZvWurdohl4x",
    name: "Large Eggs by Nice!",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2,
      zinc: 2,
      biotin: 20,
      iodine: 54,
      sodium: 140,
      calcium: 56,
      choline: 294,
      protein: 12,
      calories: 140,
      selenium: 30,
      potassium: 138,
      total_fat: 10,
      molybdenum: 16,
      riboflavin: 0.4,
      trans_fats: 0,
      cholesterol: 370,
      vitamin_b12: 0.8,
      carbohydrates: 0,
      saturated_fats: 3,
      pantothenic_acid: 2,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 50,
      },
      metric: {
        unit: "g",
        quantity: 50,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zZdkbPYRqLER",
    name: "Cage-free Brown Eggs by First Street",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2,
      sodium: 140,
      calcium: 56,
      protein: 12,
      calories: 140,
      potassium: 138,
      total_fat: 10,
      trans_fats: 0,
      cholesterol: 370,
      total_sugars: 0,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 3,
    },
    serving: {
      common: {
        unit: "egg",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 50,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zzA6GHhoPjZA",
    name: "Japanese Eggplant by Coast Produce Company",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.43,
      sodium: 0,
      calcium: 0,
      protein: 1.19,
      calories: 24,
      total_fat: 0,
      vitamin_c: 2.9,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 2.38,
      vitamin_a_iu: 0,
      carbohydrates: 5.95,
      dietary_fiber: 3.6,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 84,
      },
      metric: {
        unit: "g",
        quantity: 84,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZYyoL1rKgvQ8",
    name: "Dried Whole Egg",
    alternate_names: [
      "powdered eggs",
      "dehydrated eggs",
      "egg powder",
      "whole egg powder",
      "dried egg powder",
    ],
    description:
      "Dried whole egg is a dehydrated form of fresh eggs produced through a spray-drying process that preserves the egg's nutritional content while extending shelf life. This powder-like product maintains the protein quality of fresh eggs and can be reconstituted with water to approximate fresh eggs in most cooking applications. When properly stored in an airtight container, dried whole egg provides a shelf-stable protein source that retains its nutritional value for several months.",
    source: null,
    nutrients: {
      iron: 6.4,
      zinc: 4.08,
      water: 3.46,
      biotin: 96.75,
      copper: 0.15,
      iodine: 215,
      lysine: 3.404,
      niacin: 0.36,
      serine: 3.8,
      sodium: 497,
      valine: 3.33,
      alanine: 2.82,
      calcium: 234,
      choline: 1270,
      cystine: 1.15,
      glycine: 1.67,
      leucine: 4.32,
      omega_3: 0.28,
      omega_6: 7.76,
      omega_9: 15.9,
      proline: 1.94,
      protein: 48.8,
      taurine: 0,
      thiamin: 0.19,
      xylitol: 0,
      arginine: 3.17,
      caffeine: 0,
      calories: 583,
      chlorine: 746.5,
      chromium: 4.9,
      cysteine: 0,
      selenium: 138.6,
      sorbitol: 0,
      tyrosine: 2.05,
      histidine: 1.21,
      magnesium: 40.3,
      manganese: 0.054,
      potassium: 516,
      threonine: 2.33,
      total_fat: 41.3,
      vitamin_a: 289,
      vitamin_c: 0,
      vitamin_d: 6.6,
      vitamin_e: 5,
      vitamin_k: 1.2,
      folate_dfe: 136,
      isoleucine: 2.81,
      methionine: 1.56,
      molybdenum: 0,
      oleic_acid: 15.7,
      phosphorus: 693,
      riboflavin: 1.86,
      trans_fats: 0.17,
      tryptophan: 0.8,
      vitamin_b6: 0.42,
      capric_acid: 0,
      cholesterol: 1618,
      erucic_acid: 0,
      lauric_acid: 0,
      vitamin_b12: 3.41,
      added_sugars: 0,
      stearic_acid: 3.46,
      total_sugars: 0.47,
      aspartic_acid: 5.04,
      caprylic_acid: 0,
      carbohydrates: 2.2,
      dietary_fiber: 0,
      ethyl_alcohol: 0,
      glutamic_acid: 6.46,
      linoleic_acid: 7.05,
      myristic_acid: 0.13,
      palmitic_acid: 9.53,
      phenylalanine: 2.69,
      soluble_fiber: 0,
      linolenic_acid: 0,
      saturated_fats: 13.2,
      sugar_alcohols: 0,
      eicosenoic_acid: 0.0001,
      insoluble_fiber: 0,
      arachidonic_acid: 0.711,
      pantothenic_acid: 5.59,
      other_carbohydrates: 0,
      alpha_linolenic_acid: 0.124,
      docosahexaenoic_acid: 0.127,
      gamma_linolenic_acid: 0,
      monounsaturated_fats: 15.9,
      polyunsaturated_fats: 7.19,
      docosapentaenoic_acid: 0.014,
      eicosapentaenoic_acid: 0,
      dihomo_gamma_linolenic_acid: 0,
    },
    serving: {
      common: {
        unit: "oz",
        quantity: 0.5,
      },
      metric: {
        unit: "g",
        quantity: 14,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZyY2m32nxz1t",
    name: "Eat Smart, Veggie Snacks, Peanut Butter by Eat Smart",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.48,
      sodium: 344,
      calcium: 33,
      protein: 5.74,
      calories: 180,
      potassium: 287,
      total_fat: 9.02,
      vitamin_c: 2,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 4.1,
      vitamin_a_iu: 4920,
      carbohydrates: 20.5,
      dietary_fiber: 3.3,
      saturated_fats: 1.64,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 122,
      },
      metric: {
        unit: "g",
        quantity: 122,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zYvKRIbjFFbz",
    name: "100% Liquid Egg Whites by Stater Bros.",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 174,
      calcium: 0,
      protein: 10.9,
      calories: 54,
      potassium: 163,
      total_fat: 0,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 0,
      vitamin_a_iu: 0,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 46,
      },
      metric: {
        unit: "g",
        quantity: 46,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zYRPufLTHRgQ",
    name: "French Onion Veggie Dip by Marzetti",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 581,
      calcium: 0,
      protein: 3.23,
      calories: 387,
      total_fat: 35.5,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 65,
      total_sugars: 3.23,
      vitamin_a_iu: 0,
      carbohydrates: 9.68,
      dietary_fiber: 0,
      saturated_fats: 9.68,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 2,
      },
      metric: {
        unit: "g",
        quantity: 31,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zy7Ftm1aEgso",
    name: "The Amazing Egg by Essential Everyday",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.74,
      zinc: 1.3,
      sodium: 185,
      calcium: 26,
      protein: 10.9,
      thiamin: 0,
      calories: 54,
      potassium: 163,
      total_fat: 0,
      folic_acid: 91,
      riboflavin: 1.48,
      trans_fats: 0,
      vitamin_b6: 0.174,
      cholesterol: 0,
      vitamin_b12: 2.61,
      total_folate: 89,
      total_sugars: 0,
      vitamin_a_iu: 217,
      vitamin_d_iu: 78,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 0,
      pantothenic_acid: 1.63,
      monounsaturated_fats: 0,
      polyunsaturated_fats: 0,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 3,
      },
      metric: {
        unit: "g",
        quantity: 46,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zXITYv2lp0yS",
    name: "Organic Pasture Raised Eggs by Mary's",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.44,
      sodium: 130,
      calcium: 40,
      protein: 12,
      calories: 140,
      total_fat: 9,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 430,
      vitamin_a_iu: 600,
      carbohydrates: 2,
      saturated_fats: 3,
    },
    serving: {
      common: {
        unit: "egg",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 50,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZxGbM76Uum80",
    name: "Durham-ellis Pecan Co, Veggie Chips by Ellis Pecan Co.",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2.57,
      sodium: 268,
      calcium: 71,
      protein: 3.57,
      calories: 450,
      total_fat: 21.4,
      vitamin_c: 12.9,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 17.9,
      vitamin_a_iu: 1430,
      carbohydrates: 60.7,
      dietary_fiber: 10.7,
      saturated_fats: 3.57,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 28,
      },
      metric: {
        unit: "g",
        quantity: 28,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zXbd5J46zGRp",
    name: "Bell Pepper & Cheese Fluffy Mini Muffin Shaped Eggs Three Cheese Blend Egg Bites, Bell Pepper & Cheese by Valley Fine Foods Company",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.11,
      sodium: 262,
      calcium: 154,
      protein: 13.1,
      calories: 215,
      potassium: 54,
      total_fat: 16.9,
      trans_fats: 0,
      cholesterol: 188,
      total_sugars: 0.77,
      vitamin_d_iu: 18,
      carbohydrates: 2.31,
      dietary_fiber: 0.8,
      saturated_fats: 8.46,
    },
    serving: {
      common: {
        unit: "package",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 130,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zWugb9iKViIL",
    name: "Avocado Eggrolls by The Cheesecake Factory",
    alternate_names: [],
    description:
      "The Cheesecake Factory Avocado Egg Rolls are a popular appetizer featuring crispy egg roll wrappers filled with a creamy blend of diced avocado, sun-dried tomatoes, red onion, cilantro, and seasonings. They are deep-fried until golden and served hot with a tangy cilantro‐cashew dipping sauce that adds a zesty contrast. The dish is celebrated for its satisfying mix of crunchy exterior and smooth, flavorful interior.",
    source: null,
    nutrients: {
      iron: 0.625,
      zinc: 0.3,
      water: 55,
      biotin: 0.5,
      copper: 0.075,
      iodine: 7.5,
      lysine: 0.2625,
      niacin: 0.5,
      serine: 0.1975,
      sodium: 325,
      valine: 0.1975,
      alanine: 0.1525,
      calcium: 15,
      choline: 37.5,
      cystine: 0.0225,
      glycine: 0.175,
      leucine: 0.285,
      omega_3: 0.25,
      omega_6: 3.25,
      omega_9: 7,
      proline: 0.1525,
      protein: 3.5,
      taurine: 0,
      thiamin: 0.025,
      xylitol: 0,
      arginine: 0.22,
      caffeine: 0,
      calories: 232.5,
      chlorine: 50,
      chromium: 1.25,
      cysteine: 0.045,
      selenium: 3.75,
      sorbitol: 0,
      tyrosine: 0.11,
      histidine: 0.11,
      magnesium: 10,
      manganese: 0.1,
      potassium: 100,
      threonine: 0.1325,
      total_fat: 12,
      vitamin_a: 20,
      vitamin_c: 2.5,
      vitamin_d: 0,
      vitamin_e: 0.25,
      vitamin_k: 6.25,
      folate_dfe: 10,
      isoleucine: 0.175,
      methionine: 0.0875,
      molybdenum: 2.5,
      oleic_acid: 6.25,
      phosphorus: 37.5,
      riboflavin: 0.025,
      trans_fats: 0,
      tryptophan: 0.045,
      vitamin_b6: 0.1,
      capric_acid: 0.05,
      cholesterol: 27.5,
      erucic_acid: 0.25,
      lauric_acid: 0.075,
      vitamin_b12: 0.075,
      added_sugars: 3.75,
      stearic_acid: 0.35,
      total_sugars: 9.5,
      aspartic_acid: 0.3275,
      caprylic_acid: 0.025,
      carbohydrates: 27.75,
      dietary_fiber: 3.5,
      ethyl_alcohol: 0,
      glutamic_acid: 0.6575,
      linoleic_acid: 3,
      myristic_acid: 0.3,
      palmitic_acid: 0.575,
      phenylalanine: 0.1525,
      soluble_fiber: 0.75,
      linolenic_acid: 0.125,
      saturated_fats: 1.5,
      sugar_alcohols: 0,
      eicosenoic_acid: 0.5,
      insoluble_fiber: 2.75,
      arachidonic_acid: 0.05,
      pantothenic_acid: 0.125,
      other_carbohydrates: 0,
      alpha_linolenic_acid: 0.25,
      docosahexaenoic_acid: 0,
      gamma_linolenic_acid: 0.125,
      monounsaturated_fats: 7,
      polyunsaturated_fats: 3.5,
      docosapentaenoic_acid: 0,
      eicosapentaenoic_acid: 0,
      dihomo_gamma_linolenic_acid: 0.075,
    },
    serving: {
      common: {
        unit: "order",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 400,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZwQZDxoXkeQU",
    name: "Hummus & Veggie Snack Tray by Papa John's Salads & Produce",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.34,
      sodium: 320,
      calcium: 37,
      protein: 4.46,
      calories: 145,
      total_fat: 6.69,
      vitamin_c: 6.7,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 2.97,
      vitamin_a_iu: 186,
      carbohydrates: 20.8,
      dietary_fiber: 2.6,
      saturated_fats: 0.37,
    },
    serving: {
      common: {
        unit: "package",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 269,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZVVRnN5b4akd",
    name: "Black Truffle Arrabbiata by Actual Veggies",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.8,
      sodium: 904,
      calcium: 22,
      protein: 1.6,
      calories: 120,
      potassium: 270,
      total_fat: 9.6,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 2.4,
      total_sugars: 5.6,
      vitamin_d_iu: 0,
      carbohydrates: 8.8,
      dietary_fiber: 1.6,
      saturated_fats: 1.6,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 0.5,
      },
      metric: {
        unit: "g",
        quantity: 125,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zVCaaVFSzB5h",
    name: "Black Beans & Kale Veggie by That's It.",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2.86,
      sodium: 43,
      calcium: 151,
      protein: 11.4,
      calories: 229,
      potassium: 386,
      total_fat: 0,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 14.3,
      total_sugars: 20,
      vitamin_d_iu: 0,
      carbohydrates: 51.4,
      dietary_fiber: 11.4,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 35,
      },
      metric: {
        unit: "g",
        quantity: 35,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZUz44hutjEFB",
    name: "Extra Wide Egg Noodles by Best Choice",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3.21,
      niacin: 5.36,
      sodium: 27,
      calcium: 0,
      protein: 14.3,
      thiamin: 1,
      calories: 393,
      total_fat: 5.36,
      vitamin_c: 0,
      riboflavin: 0.304,
      trans_fats: 0,
      cholesterol: 98,
      total_folate: 214,
      total_sugars: 3.57,
      vitamin_a_iu: 0,
      carbohydrates: 71.4,
      dietary_fiber: 1.8,
      saturated_fats: 1.79,
      monounsaturated_fats: 0.89,
      polyunsaturated_fats: 1.79,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 56,
      },
      metric: {
        unit: "g",
        quantity: 56,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zuqjGdqr3nF5",
    name: "Cold Spring Farms, Extra Large Fresh Eggs by S & R Egg Farms",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.93,
      sodium: 143,
      calcium: 71,
      protein: 12.5,
      calories: 143,
      potassium: 134,
      total_fat: 8.93,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 375,
      vitamin_a_iu: 536,
      carbohydrates: 0,
      saturated_fats: 3.57,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 56,
      },
      metric: {
        unit: "g",
        quantity: 56,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zUMx2rx9c492",
    name: "Shoprite, Fine Egg Noodles, Enriched Noodle Product by Shoprite",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3.21,
      niacin: 7.14,
      sodium: 27,
      calcium: 36,
      protein: 14.3,
      thiamin: 1,
      calories: 393,
      total_fat: 5.36,
      vitamin_c: 0,
      riboflavin: 0.455,
      trans_fats: 0,
      cholesterol: 116,
      total_sugars: 3.57,
      vitamin_a_iu: 0,
      carbohydrates: 71.4,
      dietary_fiber: 3.6,
      saturated_fats: 1.79,
      monounsaturated_fats: 0.89,
      polyunsaturated_fats: 1.79,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 56,
      },
      metric: {
        unit: "g",
        quantity: 56,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZUKVbcimqxgL",
    name: "Char-grilled Veggie Burgers by Heinen's",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 4.23,
      sodium: 803,
      calcium: 141,
      protein: 22.5,
      calories: 141,
      potassium: 127,
      total_fat: 2.11,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 0,
      vitamin_d_iu: 0,
      carbohydrates: 7.04,
      dietary_fiber: 5.6,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "patty",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 71,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZukGvrh3hNiY",
    name: "The Amazing Egg by Essential Everyday",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.74,
      zinc: 1.3,
      sodium: 185,
      calcium: 26,
      protein: 10.9,
      thiamin: 0,
      calories: 54,
      potassium: 163,
      total_fat: 0,
      folic_acid: 91,
      riboflavin: 1.48,
      trans_fats: 0,
      vitamin_b6: 0.174,
      cholesterol: 0,
      vitamin_b12: 2.61,
      total_folate: 89,
      total_sugars: 0,
      vitamin_a_iu: 217,
      vitamin_d_iu: 78,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 0,
      pantothenic_acid: 1.63,
      monounsaturated_fats: 0,
      polyunsaturated_fats: 0,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 3,
      },
      metric: {
        unit: "g",
        quantity: 46,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zufNO3Lnw8g0",
    name: "Scotch Egg",
    alternate_names: [
      "Scottish Egg",
      "Breaded Sausage Egg",
      "British Scotch Egg",
      "Pub Scotch Egg",
      "English Scotch Egg",
    ],
    description:
      "A Scotch egg is a traditional British pub dish consisting of a whole boiled egg encased in seasoned sausage meat and crispy breadcrumbs. This hearty appetizer is typically deep-fried until golden brown, creating distinct textural layers from its crunchy exterior to its tender meat and egg center. Popular as both a hot pub snack or cold picnic fare, this protein-rich dish offers a substantial combination of meat and egg protein in a convenient, hand-held format.",
    source: null,
    nutrients: {
      iron: 1.7699,
      zinc: 1.7699,
      water: 48.6726,
      biotin: 8.8496,
      copper: 0.0885,
      iodine: 13.2743,
      lysine: 0.6637,
      niacin: 2.6549,
      serine: 0.4956,
      sodium: 318.5841,
      valine: 0.4956,
      alanine: 0.5398,
      calcium: 44.2478,
      choline: 123.8938,
      cystine: 0.0442,
      glycine: 0.3894,
      leucine: 0.7345,
      omega_3: 0.3628,
      omega_6: 3.2655,
      omega_9: 6.6372,
      proline: 0.4425,
      protein: 9.823,
      taurine: 4.4248,
      thiamin: 0.177,
      xylitol: 0,
      arginine: 0.469,
      caffeine: 0,
      calories: 234.5133,
      chlorine: 482.3009,
      chromium: 0.885,
      cysteine: 0.2124,
      selenium: 17.6991,
      sorbitol: 0,
      tyrosine: 0.3451,
      histidine: 0.1947,
      magnesium: 17.6991,
      manganese: 0.0885,
      potassium: 132.7434,
      threonine: 0.3894,
      total_fat: 14.6018,
      vitamin_a: 88.4956,
      vitamin_c: 0.885,
      vitamin_d: 0.885,
      vitamin_e: 0.4425,
      vitamin_k: 0.2655,
      folate_dfe: 26.5487,
      isoleucine: 0.4425,
      methionine: 0.2478,
      molybdenum: 2.6549,
      oleic_acid: 5.7522,
      phosphorus: 123.8938,
      riboflavin: 0.2655,
      trans_fats: 0,
      tryptophan: 0.1239,
      vitamin_b6: 0.177,
      capric_acid: 0.2655,
      cholesterol: 185.8407,
      erucic_acid: 0.2655,
      lauric_acid: 0.2655,
      vitamin_b12: 1.0619,
      added_sugars: 0.4425,
      stearic_acid: 1.1504,
      total_sugars: 0.885,
      aspartic_acid: 1.0354,
      caprylic_acid: 0.2655,
      carbohydrates: 14.8673,
      dietary_fiber: 1.3274,
      ethyl_alcohol: 0,
      glutamic_acid: 1.4779,
      linoleic_acid: 3.0973,
      myristic_acid: 0.6195,
      palmitic_acid: 1.7699,
      phenylalanine: 0.3894,
      soluble_fiber: 0.4425,
      linolenic_acid: 0,
      saturated_fats: 4.3363,
      sugar_alcohols: 0,
      eicosenoic_acid: 0.6195,
      insoluble_fiber: 0.885,
      arachidonic_acid: 0.0354,
      pantothenic_acid: 0.885,
      other_carbohydrates: 12.6549,
      alpha_linolenic_acid: 0.3097,
      docosahexaenoic_acid: 0.0088,
      gamma_linolenic_acid: 0.0442,
      monounsaturated_fats: 6.6372,
      polyunsaturated_fats: 3.6283,
      docosapentaenoic_acid: 0.0177,
      eicosapentaenoic_acid: 0.0265,
      dihomo_gamma_linolenic_acid: 0.0885,
    },
    serving: {
      common: {
        unit: "scotch egg",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 113,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZUcbF0R4zwCy",
    name: "Tropical Dragon Wholesome Fruit & Veggie Smoothie, Tropical Dragon by Suja",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.56,
      sodium: 8,
      calcium: 24,
      protein: 2.26,
      calories: 65,
      potassium: 115,
      total_fat: 1.69,
      vitamin_c: 5.6,
      total_sugars: 5.37,
      carbohydrates: 9.04,
      dietary_fiber: 2,
    },
    serving: {
      common: {
        unit: "oz",
        quantity: 12,
      },
      metric: {
        unit: "ml",
        quantity: 354,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZUaPJPl9ZV4M",
    name: "Vegetable Egg Roll by 365 Everyday Value",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.76,
      sodium: 294,
      calcium: 35,
      protein: 5.88,
      calories: 212,
      potassium: 188,
      total_fat: 7.06,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 1.2,
      total_sugars: 2.35,
      vitamin_d_iu: 0,
      carbohydrates: 31.8,
      dietary_fiber: 2.4,
      saturated_fats: 0.59,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 85,
      },
      metric: {
        unit: "g",
        quantity: 85,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zTXNb8eSN9V7",
    name: "Egg Substitute by Shoprite",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.74,
      zinc: 1.3,
      sodium: 185,
      calcium: 22,
      protein: 10.9,
      thiamin: 0,
      calories: 54,
      potassium: 152,
      total_fat: 0,
      folic_acid: 87,
      riboflavin: 1.48,
      trans_fats: 0,
      vitamin_b6: 0.174,
      cholesterol: 0,
      vitamin_b12: 2.61,
      total_folate: 85,
      total_sugars: 0,
      vitamin_a_iu: 217,
      vitamin_d_iu: 78,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 0,
      pantothenic_acid: 1.63,
      monounsaturated_fats: 0,
      polyunsaturated_fats: 0,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 3,
      },
      metric: {
        unit: "g",
        quantity: 46,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZTRSencUrID8",
    name: "Peach Mango Medley Fruit & Veggie Bars, Peach Mango Medley by Outshine",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 6,
      calcium: 0,
      protein: 0,
      calories: 91,
      total_fat: 0,
      vitamin_c: 19.5,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 20.8,
      vitamin_a_iu: 974,
      carbohydrates: 22.1,
      dietary_fiber: 0,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 77,
      },
      metric: {
        unit: "g",
        quantity: 77,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zTE9GCt1o1d7",
    name: "Tiny Jelly Eggs by Ahold",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 0,
      calcium: 0,
      protein: 0,
      calories: 533,
      total_fat: 0,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 86.7,
      total_sugars: 86.7,
      vitamin_d_iu: 0,
      carbohydrates: 93.3,
      dietary_fiber: 0,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "piece",
        quantity: 23,
      },
      metric: {
        unit: "g",
        quantity: 30,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zT8NpFGCSITQ",
    name: "Muddy Bites by Simply Eggless",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3,
      sodium: 167,
      calcium: 100,
      protein: 6.67,
      calories: 467,
      potassium: 233,
      total_fat: 15,
      trans_fats: 0,
      cholesterol: 17,
      added_sugars: 40,
      total_sugars: 43.3,
      vitamin_d_iu: 0,
      carbohydrates: 73.3,
      dietary_fiber: 3.3,
      saturated_fats: 8.33,
    },
    serving: {
      common: {
        unit: "cone",
        quantity: 6,
      },
      metric: {
        unit: "g",
        quantity: 30,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZT7ypb6D5Unr",
    name: "Yves Veggie Cuisine Sans-viande Haché Original by Yves Veggie Cuisine",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 4.91,
      zinc: 6.82,
      niacin: 12.7,
      sodium: 491,
      calcium: 73,
      protein: 18.2,
      thiamin: 1,
      calories: 109,
      potassium: 509,
      total_fat: 0.91,
      vitamin_c: 0,
      riboflavin: 0.464,
      trans_fats: 0,
      vitamin_b6: 0.727,
      cholesterol: 0,
      vitamin_b12: 2.73,
      total_sugars: 1.82,
      vitamin_a_iu: 0,
      carbohydrates: 9.09,
      dietary_fiber: 3.6,
      saturated_fats: 0,
      pantothenic_acid: 1.82,
      monounsaturated_fats: 0.91,
      polyunsaturated_fats: 0,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 0.33,
      },
      metric: {
        unit: "g",
        quantity: 55,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zt1QQ9dd2yho",
    name: "Reddi Wip Sweetened Grade a Dairy Whipped Topping by Egg Beaters",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      sodium: 0,
      protein: 0,
      calories: 300,
      total_fat: 20,
      cholesterol: 100,
      added_sugars: 20,
      total_sugars: 20,
      carbohydrates: 20,
      saturated_fats: 10,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 2,
      },
      metric: {
        unit: "g",
        quantity: 5,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZSVGtCEW7oXA",
    name: "Steak and Cheese Egg Rolls",
    alternate_names: [
      "Philly Egg Rolls",
      "Cheesesteak Egg Rolls",
      "Philly Cheesesteak Rolls",
      "Philadelphia Steak Egg Rolls",
      "Cheese Steak Rolls",
    ],
    description:
      "Steak and Cheese Egg Rolls are a fusion appetizer that wraps traditional Philly cheesesteak ingredients in crispy egg roll wrappers. These deep-fried rolls feature seasoned sliced beef and melted cheese encased in a crunchy exterior, typically served as a pair with dipping sauce. While offering a creative twist on both Asian and American classics, these indulgent appetizers are notably high in calories and sodium, often containing over 500mg of sodium per piece.",
    source: null,
    nutrients: {
      iron: 1.7647,
      zinc: 4.7059,
      water: 35.2941,
      biotin: 2.3529,
      copper: 0.1176,
      iodine: 23.5294,
      lysine: 1.1765,
      niacin: 4.7059,
      serine: 0.5176,
      sodium: 658.8235,
      valine: 0.7765,
      alanine: 0.7765,
      calcium: 176.4706,
      choline: 35.2941,
      cystine: 0.1176,
      glycine: 0.5176,
      leucine: 1.0353,
      omega_3: 0.1176,
      omega_6: 0.9412,
      omega_9: 1.7647,
      proline: 0.6471,
      protein: 12.9412,
      taurine: 11.7647,
      thiamin: 0.2353,
      xylitol: 0,
      arginine: 0.7765,
      caffeine: 0,
      calories: 305.8824,
      chlorine: 395.2941,
      chromium: 2.3529,
      cysteine: 0.1176,
      selenium: 17.6471,
      sorbitol: 0,
      tyrosine: 0.5176,
      histidine: 0.3294,
      magnesium: 14.1176,
      manganese: 0.2353,
      potassium: 294.1176,
      threonine: 0.5176,
      total_fat: 7.0588,
      vitamin_a: 82.3529,
      vitamin_c: 1.1765,
      vitamin_d: 0.5882,
      vitamin_e: 1.1765,
      vitamin_k: 5.8824,
      folate_dfe: 17.6471,
      isoleucine: 0.6471,
      methionine: 0.3294,
      molybdenum: 5.8824,
      oleic_acid: 1.7647,
      phosphorus: 176.4706,
      riboflavin: 0.3529,
      trans_fats: 0,
      tryptophan: 0.1294,
      vitamin_b6: 0.3529,
      capric_acid: 0,
      cholesterol: 82.3529,
      erucic_acid: 0,
      lauric_acid: 0,
      vitamin_b12: 1.7647,
      added_sugars: 0,
      stearic_acid: 1.1765,
      total_sugars: 3.5294,
      aspartic_acid: 1.2941,
      caprylic_acid: 0,
      carbohydrates: 27.0588,
      dietary_fiber: 2.3529,
      ethyl_alcohol: 0,
      glutamic_acid: 1.9412,
      linoleic_acid: 0.9412,
      myristic_acid: 0.5882,
      palmitic_acid: 1.7647,
      phenylalanine: 0.5882,
      soluble_fiber: 0.5882,
      linolenic_acid: 0,
      saturated_fats: 3.5294,
      sugar_alcohols: 0,
      eicosenoic_acid: 0,
      insoluble_fiber: 1.7647,
      arachidonic_acid: 0.1176,
      pantothenic_acid: 0.5882,
      other_carbohydrates: 0,
      alpha_linolenic_acid: 0.1176,
      docosahexaenoic_acid: 0.0059,
      gamma_linolenic_acid: 0.0588,
      monounsaturated_fats: 2.3529,
      polyunsaturated_fats: 1.1765,
      docosapentaenoic_acid: 0.0059,
      eicosapentaenoic_acid: 0.0059,
      dihomo_gamma_linolenic_acid: 0.0588,
    },
    serving: {
      common: {
        unit: "piece",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 85,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zRtwuY6jLXLb",
    name: "Jump Rope Filled With Egg Tarts by Nice!",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 0,
      calcium: 0,
      protein: 0,
      calories: 400,
      total_fat: 0,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 80,
      vitamin_a_iu: 0,
      carbohydrates: 100,
      dietary_fiber: 0,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 15,
      },
      metric: {
        unit: "g",
        quantity: 15,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zrSjqjb7B7rH",
    name: "Fruit Cordial Eggs in Dark Chocolate by Koppers Chocolate Specialty Co",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2.7,
      sodium: 0,
      calcium: 0,
      protein: 2.5,
      calories: 450,
      total_fat: 15,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 80,
      vitamin_a_iu: 0,
      carbohydrates: 87.5,
      dietary_fiber: 2.5,
      saturated_fats: 8.75,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 40,
      },
      metric: {
        unit: "g",
        quantity: 40,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zqYIE2X58TIk",
    name: "Grilled Veggies by Green Giant",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.4,
      sodium: 0,
      calcium: 20,
      protein: 2.02,
      calories: 51,
      potassium: 444,
      total_fat: 0,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 0,
      total_sugars: 6.06,
      vitamin_d_iu: 0,
      carbohydrates: 11.1,
      dietary_fiber: 5.1,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "package",
        quantity: 0.25,
      },
      metric: {
        unit: "g",
        quantity: 99,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZqyGa2gYYkv0",
    name: "Dove Eggs by M&M's",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3.72,
      sodium: 0,
      calcium: 0,
      protein: 6.9,
      calories: 517,
      potassium: 483,
      total_fat: 31,
      vitamin_d: 0,
      trans_fats: 0,
      cholesterol: 17,
      added_sugars: 44.8,
      total_sugars: 44.8,
      carbohydrates: 58.6,
      dietary_fiber: 6.9,
      saturated_fats: 17.2,
    },
    serving: {
      common: {
        unit: "piece",
        quantity: 4,
      },
      metric: {
        unit: "g",
        quantity: 29,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZqXxDE3hcF9E",
    name: "Nature's Promise Eggnog by Ahold",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 79,
      calcium: 125,
      protein: 4.17,
      calories: 150,
      potassium: 167,
      total_fat: 7.5,
      trans_fats: 0,
      cholesterol: 50,
      added_sugars: 13.3,
      total_sugars: 17.5,
      vitamin_d_iu: 0,
      carbohydrates: 18.3,
      dietary_fiber: 0,
      saturated_fats: 4.17,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 0.5,
      },
      metric: {
        unit: "ml",
        quantity: 120,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zQkxLdv8DKAS",
    name: "Freeze-dried Edamame Veggie Snack by Greenwave Foods",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 9,
      sodium: 800,
      calcium: 200,
      protein: 40,
      calories: 450,
      total_fat: 20,
      vitamin_a: 135,
      vitamin_c: 18,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 5,
      carbohydrates: 35,
      dietary_fiber: 15,
      saturated_fats: 2.5,
    },
    serving: {
      common: {
        unit: "bag",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 20,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zQIfCSCubvYY",
    name: "Egg Substitute by Shoprite",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.74,
      zinc: 1.3,
      sodium: 185,
      calcium: 22,
      protein: 10.9,
      thiamin: 0,
      calories: 54,
      potassium: 152,
      total_fat: 0,
      folic_acid: 87,
      riboflavin: 1.48,
      trans_fats: 0,
      vitamin_b6: 0.174,
      cholesterol: 0,
      vitamin_b12: 2.61,
      total_folate: 85,
      total_sugars: 0,
      vitamin_a_iu: 217,
      vitamin_d_iu: 78,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 0,
      pantothenic_acid: 1.63,
      monounsaturated_fats: 0,
      polyunsaturated_fats: 0,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 3,
      },
      metric: {
        unit: "g",
        quantity: 46,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zq8qDu7e5zvl",
    name: "White Creme Peanut Butter Eggs by Hershey's",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.76,
      sodium: 368,
      calcium: 147,
      protein: 11.8,
      calories: 529,
      potassium: 412,
      total_fat: 29.4,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 38.2,
      total_sugars: 44.1,
      carbohydrates: 52.9,
      dietary_fiber: 2.9,
      saturated_fats: 10.3,
    },
    serving: {
      common: {
        unit: "piece",
        quantity: 2,
      },
      metric: {
        unit: "g",
        quantity: 34,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zq8Emiklhsf9",
    name: "Cheese & Spinach Ravioli with Marinara Sauce Happysqueeze Organic Veggies Bowl by Happysqueeze",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.09,
      sodium: 78,
      calcium: 31,
      protein: 3.12,
      calories: 86,
      potassium: 141,
      total_fat: 0.78,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 3.12,
      vitamin_d_iu: 0,
      carbohydrates: 17.2,
      dietary_fiber: 2.3,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "bowl",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 128,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zq88ixHRQLOi",
    name: "Fresh Eggs by Shaw's",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.44,
      sodium: 130,
      calcium: 40,
      protein: 12,
      calories: 140,
      total_fat: 9,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 430,
      vitamin_a_iu: 600,
      carbohydrates: 2,
      saturated_fats: 3,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 50,
      },
      metric: {
        unit: "g",
        quantity: 50,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zpyo8MMXUgPG",
    name: "Medium Egg Noodles by Creamette",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3.39,
      niacin: 7.14,
      sodium: 18,
      calcium: 0,
      protein: 14.3,
      thiamin: 1,
      calories: 375,
      potassium: 232,
      total_fat: 4.46,
      vitamin_d: 0,
      folic_acid: 196,
      riboflavin: 0.455,
      trans_fats: 0,
      cholesterol: 107,
      added_sugars: 0,
      total_sugars: 3.57,
      carbohydrates: 69.6,
      dietary_fiber: 3.6,
      saturated_fats: 0.89,
      monounsaturated_fats: 0.89,
      polyunsaturated_fats: 1.79,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 56,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zPxN7M9PF3NX",
    name: "Homestyle Egg Noodles by Good & Gather",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.8,
      sodium: 17,
      calcium: 0,
      protein: 6.67,
      calories: 150,
      total_fat: 1.67,
      vitamin_a: 0,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 42,
      total_sugars: 0,
      carbohydrates: 28.3,
      dietary_fiber: 0,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 0.5,
      },
      metric: {
        unit: "g",
        quantity: 60,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zPJrcM2LqBAg",
    name: "Grade a Extra Large One Dozen Eggs by Best Choice",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.79,
      sodium: 143,
      calcium: 55,
      protein: 12.5,
      calories: 143,
      potassium: 138,
      total_fat: 8.93,
      trans_fats: 0,
      cholesterol: 375,
      total_sugars: 0,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 3.57,
    },
    serving: {
      common: {
        unit: "egg",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 56,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZPgSpJjiI10r",
    name: "Egg - Caramel by Russell Stover",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.08,
      sodium: 189,
      calcium: 127,
      protein: 5.41,
      calories: 459,
      potassium: 214,
      total_fat: 21.6,
      trans_fats: 0,
      cholesterol: 27,
      added_sugars: 45.9,
      total_sugars: 51.4,
      vitamin_d_iu: 0,
      carbohydrates: 62.2,
      dietary_fiber: 2.7,
      saturated_fats: 16.2,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 37,
      },
      metric: {
        unit: "g",
        quantity: 37,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zP7aEMVLqrbm",
    name: "Country Style Egg Noodles, Country Style by Hyvee",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3,
      sodium: 25,
      calcium: 33,
      protein: 10,
      calories: 283,
      total_fat: 3.33,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 108,
      total_sugars: 1.67,
      vitamin_a_iu: 167,
      carbohydrates: 53.3,
      dietary_fiber: 1.7,
      saturated_fats: 0.83,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 60,
      },
      metric: {
        unit: "g",
        quantity: 60,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zp17EBOibMyy",
    name: "Romaine Lettuce, Turkey Breast, Eggs, Tomatoes, Cheese, and Served With Ranch Dressing, Chef Salad by Good & Gather",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.68,
      sodium: 292,
      calcium: 88,
      protein: 8.31,
      calories: 149,
      total_fat: 11.6,
      vitamin_a: 703,
      vitamin_c: 3,
      trans_fats: 0,
      cholesterol: 58,
      total_sugars: 1.51,
      carbohydrates: 3.02,
      dietary_fiber: 1,
      saturated_fats: 3.27,
    },
    serving: {
      common: {
        unit: "salad",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 397,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZOYysaaoYSNY",
    name: "Stuffed Durum Semolina & Egg Pasta, Italian Sausage Tortellini by Wegmans",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2.45,
      sodium: 373,
      calcium: 36,
      protein: 12.7,
      calories: 291,
      total_fat: 8.18,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 68,
      total_sugars: 2.73,
      vitamin_a_iu: 0,
      carbohydrates: 43.6,
      dietary_fiber: 2.7,
      saturated_fats: 1.82,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 110,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZotWRDOw6B0b",
    name: "Egg Salad on a Croissant by Taylor Farms",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.93,
      sodium: 401,
      calcium: 53,
      protein: 9.63,
      calories: 251,
      total_fat: 16.6,
      vitamin_c: 0.6,
      trans_fats: 0,
      cholesterol: 230,
      total_sugars: 2.14,
      vitamin_a_iu: 1200,
      carbohydrates: 16.6,
      dietary_fiber: 0.5,
      saturated_fats: 6.42,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 187,
      },
      metric: {
        unit: "g",
        quantity: 187,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZOn1UvacPCRw",
    name: "Hot Veggie (Grilled Veggie Sub #54), Wrap by Jersey Mike's Subs",
    alternate_names: [],
    description:
      "The Hot Veggie (Grilled Veggie Sub #54) from Jersey Mike's Subs features a hearty blend of grilled onions, peppers, mushrooms, and melted mozzarella cheese served on a freshly baked sub roll. It is prepared with caramelized vegetables and can be customized with fresh lettuce, tomato, and Mike’s Way seasonings to add an extra burst of flavor.",
    source: null,
    nutrients: {
      iron: 0.8571,
      zinc: 0.5714,
      water: 40,
      biotin: 0.5714,
      copper: 0.0571,
      iodine: 4.2857,
      lysine: 0.3429,
      niacin: 1.1429,
      serine: 0.2571,
      sodium: 271.4286,
      valine: 0.2857,
      alanine: 0.4286,
      calcium: 57.1429,
      choline: 5.7143,
      cystine: 0.0286,
      glycine: 0.3143,
      leucine: 0.4571,
      omega_3: 0.0857,
      omega_6: 0.4286,
      omega_9: 1.1429,
      proline: 0.5143,
      protein: 7.1429,
      taurine: 0,
      thiamin: 0.0857,
      xylitol: 0,
      arginine: 0.3429,
      caffeine: 0,
      calories: 194.2857,
      chlorine: 57.1429,
      chromium: 1.4286,
      cysteine: 0.0857,
      selenium: 5.7143,
      sorbitol: 0,
      tyrosine: 0.2,
      histidine: 0.1429,
      magnesium: 8.5714,
      manganese: 0.1143,
      potassium: 114.2857,
      threonine: 0.2286,
      total_fat: 8,
      vitamin_a: 85.7143,
      vitamin_c: 2.8571,
      vitamin_d: 5.7143,
      vitamin_e: 0.1429,
      vitamin_k: 8.5714,
      folate_dfe: 34.2857,
      isoleucine: 0.2571,
      methionine: 0.1143,
      molybdenum: 2.8571,
      oleic_acid: 1.1429,
      phosphorus: 71.4286,
      riboflavin: 0.1143,
      trans_fats: 0.1429,
      tryptophan: 0.0571,
      vitamin_b6: 0.0857,
      capric_acid: 0.0286,
      cholesterol: 11.4286,
      erucic_acid: 0,
      lauric_acid: 0.0571,
      vitamin_b12: 0.3429,
      added_sugars: 0.5714,
      stearic_acid: 1.1429,
      total_sugars: 1.7143,
      aspartic_acid: 0.5714,
      caprylic_acid: 0.0286,
      carbohydrates: 23.4286,
      dietary_fiber: 1.7143,
      ethyl_alcohol: 0,
      glutamic_acid: 0.8571,
      linoleic_acid: 0.3714,
      myristic_acid: 0.1143,
      palmitic_acid: 1.4286,
      phenylalanine: 0.2571,
      soluble_fiber: 0.5714,
      linolenic_acid: 0.0571,
      saturated_fats: 2.8571,
      sugar_alcohols: 0,
      eicosenoic_acid: 0.0571,
      insoluble_fiber: 1.1429,
      arachidonic_acid: 0,
      pantothenic_acid: 0.2,
      other_carbohydrates: 0,
      alpha_linolenic_acid: 0.0857,
      docosahexaenoic_acid: 0,
      gamma_linolenic_acid: 0.0286,
      monounsaturated_fats: 2.5714,
      polyunsaturated_fats: 2,
      docosapentaenoic_acid: 0,
      eicosapentaenoic_acid: 0,
      dihomo_gamma_linolenic_acid: 0.0286,
    },
    serving: {
      common: {
        name: "Wrap",
        unit: "wrap",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 350,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZObj7lT36ZPr",
    name: "Veggie-go's, Tropikale Organic Chewy Fruit & Veggie Snacks by Veggie-Go's",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 6,
      sodium: 42,
      calcium: 167,
      protein: 8.33,
      calories: 250,
      total_fat: 0,
      vitamin_c: 225,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 41.7,
      vitamin_a_iu: 33300,
      carbohydrates: 66.7,
      dietary_fiber: 16.7,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 12,
      },
      metric: {
        unit: "g",
        quantity: 12,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zo90swBL9TpR",
    name: "Pasture Raised Grade a Large Brown Eggs by Kroger",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2,
      sodium: 140,
      calcium: 56,
      protein: 12,
      calories: 140,
      potassium: 138,
      total_fat: 10,
      cholesterol: 370,
      vitamin_d_iu: 80,
      carbohydrates: 0,
      saturated_fats: 3,
    },
    serving: {
      common: {
        unit: "egg",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 50,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZO2Zh1WZZrUz",
    name: "Albertsons Bakery, Egg Bagel by West Coast Grocery Company",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3.16,
      sodium: 421,
      calcium: 0,
      protein: 7.02,
      calories: 246,
      total_fat: 0.88,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 9,
      total_sugars: 3.51,
      vitamin_a_iu: 0,
      carbohydrates: 50.9,
      dietary_fiber: 1.8,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "bagel",
        quantity: 0.5,
      },
      metric: {
        unit: "g",
        quantity: 57,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZnrwSTzkX47b",
    name: "Cauliflower Crust Pizza Veggie by Madewith",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.4,
      sodium: 469,
      calcium: 186,
      protein: 6.99,
      calories: 189,
      potassium: 245,
      total_fat: 7.69,
      trans_fats: 0,
      cholesterol: 21,
      added_sugars: 2.8,
      total_sugars: 4.9,
      vitamin_d_iu: 0,
      carbohydrates: 23.8,
      dietary_fiber: 2.1,
      saturated_fats: 4.2,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 143,
      },
      metric: {
        unit: "g",
        quantity: 143,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zNnsnFauy9Tx",
    name: "Egg Replacer by Kroger",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 8.57,
      sodium: 0,
      calcium: 429,
      protein: 28.6,
      calories: 357,
      potassium: 1000,
      total_fat: 7.14,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 0,
      vitamin_d_iu: 0,
      carbohydrates: 57.1,
      dietary_fiber: 28.6,
      saturated_fats: 0,
      monounsaturated_fats: 0,
      polyunsaturated_fats: 0,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 7,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZNjXpfHRG3ip",
    name: "Fruit & Veggie Strip, Wildberry Apple by Pure Organic",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 107,
      calcium: 0,
      protein: 0,
      calories: 321,
      potassium: 786,
      total_fat: 0,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 57.1,
      vitamin_a_iu: 3570,
      carbohydrates: 78.6,
      dietary_fiber: 7.1,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 14,
      },
      metric: {
        unit: "g",
        quantity: 14,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZnjtBp0ioN42",
    name: "Extra Broad Egg Noodles by Harris Teeter",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3.39,
      niacin: 7.14,
      sodium: 18,
      calcium: 0,
      protein: 14.3,
      thiamin: 1,
      calories: 375,
      potassium: 232,
      total_fat: 4.46,
      folic_acid: 196,
      riboflavin: 0.455,
      trans_fats: 0,
      cholesterol: 107,
      total_folate: 214,
      total_sugars: 3.57,
      vitamin_d_iu: 0,
      carbohydrates: 69.6,
      dietary_fiber: 3.6,
      saturated_fats: 0.89,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 56,
      },
      metric: {
        unit: "g",
        quantity: 56,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zni4lo1GasKY",
    name: "Large White Eggs by Wild Oats",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.44,
      sodium: 140,
      calcium: 40,
      protein: 12,
      calories: 140,
      total_fat: 10,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 370,
      vitamin_a_iu: 600,
      carbohydrates: 0,
      saturated_fats: 3,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 50,
      },
      metric: {
        unit: "g",
        quantity: 50,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZnBuWqOEnUgK",
    name: "Egg Nog by Dean Foods Company",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 88,
      calcium: 125,
      protein: 3.33,
      calories: 142,
      potassium: 150,
      total_fat: 6.67,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 50,
      total_sugars: 15,
      vitamin_a_iu: 250,
      carbohydrates: 15.8,
      dietary_fiber: 0,
      saturated_fats: 4.17,
    },
    serving: {
      common: {
        unit: "ml",
        quantity: 120,
      },
      metric: {
        unit: "ml",
        quantity: 120,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zn6DSUsXwQZt",
    name: "Veggie Lover's Pizza, Large (1 slice, 1/8 pizza) by Pizza Hut",
    alternate_names: [],
    description:
      "The Veggie Lover's Pizza from Pizza Hut is a vegetarian-friendly option loaded with a colorful array of fresh vegetables. It features sliced tomatoes, mushrooms, black olives, red onions, green bell peppers, and sweet banana peppers atop a traditional pan crust with a choice of classic or spicy marinara sauce. The pizza delivers a balanced nutritional profile with a satisfying mix of protein, fats, and carbohydrates in each slice.",
    source: null,
    nutrients: {
      iron: 1.3333,
      zinc: 0.9037,
      water: 51.8519,
      biotin: 1.7778,
      copper: 0.0889,
      iodine: 17.7778,
      lysine: 0.5704,
      niacin: 1.7778,
      serine: 0.2741,
      sodium: 511.1111,
      valine: 0.5704,
      alanine: 0.4889,
      calcium: 180.7407,
      choline: 17.7778,
      cystine: 0.0444,
      glycine: 0.2741,
      leucine: 0.7333,
      omega_3: 0.0444,
      omega_6: 1.7778,
      omega_9: 2.7111,
      proline: 0.7333,
      protein: 8.1481,
      taurine: 0,
      thiamin: 0.1778,
      xylitol: 0,
      arginine: 0.5704,
      caffeine: 0,
      calories: 200,
      chlorine: 135.5556,
      chromium: 0.9037,
      cysteine: 0.0444,
      selenium: 8.8889,
      sorbitol: 0,
      tyrosine: 0.2741,
      histidine: 0.2444,
      magnesium: 17.7778,
      manganese: 0.1778,
      potassium: 180.7407,
      threonine: 0.3259,
      total_fat: 8.1481,
      vitamin_a: 108.1481,
      vitamin_c: 1.7778,
      vitamin_d: 0.8889,
      vitamin_e: 0.8889,
      vitamin_k: 4.5185,
      folate_dfe: 17.7778,
      isoleucine: 0.4074,
      methionine: 0.1778,
      molybdenum: 1.7778,
      oleic_acid: 2.7111,
      phosphorus: 135.5556,
      riboflavin: 0.1778,
      trans_fats: 0.1481,
      tryptophan: 0.0815,
      vitamin_b6: 0.0889,
      capric_acid: 0.0889,
      cholesterol: 25.9259,
      erucic_acid: 0.1778,
      lauric_acid: 0.0889,
      vitamin_b12: 0.4519,
      added_sugars: 0.8889,
      stearic_acid: 0.8148,
      total_sugars: 2.963,
      aspartic_acid: 0.8148,
      caprylic_acid: 0.0889,
      carbohydrates: 24.4444,
      dietary_fiber: 1.8519,
      ethyl_alcohol: 0,
      glutamic_acid: 1.6296,
      linoleic_acid: 1.5556,
      myristic_acid: 0.6296,
      palmitic_acid: 1.6296,
      phenylalanine: 0.3259,
      soluble_fiber: 0.4444,
      linolenic_acid: 0.0889,
      saturated_fats: 3.1852,
      sugar_alcohols: 0,
      eicosenoic_acid: 0.2741,
      insoluble_fiber: 1.4074,
      arachidonic_acid: 0,
      pantothenic_acid: 0.2741,
      other_carbohydrates: 0,
      alpha_linolenic_acid: 0.0296,
      docosahexaenoic_acid: 0,
      gamma_linolenic_acid: 0.1333,
      monounsaturated_fats: 3.1852,
      polyunsaturated_fats: 1.7778,
      docosapentaenoic_acid: 0,
      eicosapentaenoic_acid: 0,
      dihomo_gamma_linolenic_acid: 0.0889,
    },
    serving: {
      common: {
        name: "Large (1 slice, 1/8 pizza)",
        unit: "slice",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 135,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZMxCy5211Tu4",
    name: "Mini Eggs by Lindt",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 109,
      calcium: 178,
      protein: 3.12,
      calories: 500,
      potassium: 156,
      total_fat: 21.9,
      vitamin_d: 0,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 59.4,
      total_sugars: 65.6,
      carbohydrates: 68.8,
      dietary_fiber: 0,
      saturated_fats: 14.1,
    },
    serving: {
      common: {
        unit: "egg",
        quantity: 6,
      },
      metric: {
        unit: "g",
        quantity: 32,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zmx0DXJNiNOQ",
    name: "Whole Foods Market, Veggie Chips by Whole Foods Market",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.2,
      sodium: 433,
      calcium: 67,
      protein: 3.33,
      calories: 467,
      total_fat: 13.3,
      vitamin_c: 4,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 13.3,
      vitamin_a_iu: 6670,
      carbohydrates: 80,
      dietary_fiber: 6.7,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 30,
      },
      metric: {
        unit: "g",
        quantity: 30,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZMvVrNVuSBm7",
    name: "Classic Vanilla Natural Egg White & Yolk Protein Powder, Classic Vanilla by Designer wellness",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.12,
      sodium: 1090,
      calcium: 156,
      protein: 75,
      calories: 344,
      magnesium: 62,
      potassium: 875,
      total_fat: 1.56,
      phosphorus: 62,
      riboflavin: 2.55,
      trans_fats: 0,
      cholesterol: 31,
      vitamin_b12: 5.62,
      total_sugars: 0,
      carbohydrates: 9.38,
      dietary_fiber: 0,
      saturated_fats: 0,
      pantothenic_acid: 0.469,
    },
    serving: {
      common: {
        unit: "scoop",
        quantity: 2,
      },
      metric: {
        unit: "g",
        quantity: 32,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zMJOfDWMtE6i",
    name: "Reggano Marinara Pasta Sauce by Aldi-Benner Company",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.58,
      sodium: 411,
      calcium: 16,
      protein: 1.61,
      calories: 65,
      total_fat: 2.02,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 7.26,
      vitamin_a_iu: 605,
      carbohydrates: 10.5,
      dietary_fiber: 1.6,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 124,
      },
      metric: {
        unit: "g",
        quantity: 124,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZmBVn6uavqvA",
    name: "Kohlrabi Linguine Fresh Veggie Noodles, Kohlrabi Linguine by Mann's",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 18,
      calcium: 24,
      protein: 1.18,
      calories: 29,
      potassium: 351,
      total_fat: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 2.35,
      vitamin_d_iu: 0,
      carbohydrates: 5.88,
      dietary_fiber: 3.5,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 2,
      },
      metric: {
        unit: "g",
        quantity: 85,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zlyNR2RBgTmo",
    name: "Dark Chocolate Sea Salt Caramel Eggs by Whole Foods Market",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.8,
      sodium: 150,
      calcium: 50,
      protein: 2.5,
      calories: 425,
      total_fat: 25,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 25,
      total_sugars: 45,
      vitamin_a_iu: 250,
      carbohydrates: 60,
      dietary_fiber: 2.5,
      saturated_fats: 15,
    },
    serving: {
      common: {
        unit: "pc",
        quantity: 13,
      },
      metric: {
        unit: "g",
        quantity: 40,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zluS3EputAUq",
    name: "Liquid Egg Substitute by Giant Eagle",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.74,
      zinc: 1.09,
      biotin: 3,
      sodium: 196,
      calcium: 43,
      protein: 10.9,
      thiamin: 217,
      calories: 54,
      potassium: 174,
      total_fat: 0,
      folic_acid: 98,
      riboflavin: 1.52,
      trans_fats: 0,
      vitamin_b6: 0.217,
      cholesterol: 0,
      vitamin_b12: 1.96,
      total_sugars: 0,
      vitamin_a_iu: 30400,
      vitamin_d_iu: 70,
      carbohydrates: 2.17,
      dietary_fiber: 0,
      saturated_fats: 0,
      vitamin_e_alpha: 2,
      pantothenic_acid: 1.74,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 3,
      },
      metric: {
        unit: "g",
        quantity: 46,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zLEBitW8BnTx",
    name: "Lean Cuisine, Simple Favorites, Vegetable Eggroll by Nestlé",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.71,
      sodium: 216,
      calcium: 16,
      protein: 2.75,
      calories: 118,
      potassium: 86,
      total_fat: 1.57,
      vitamin_c: 3.5,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 5.1,
      vitamin_a_iu: 784,
      carbohydrates: 23.1,
      dietary_fiber: 1.2,
      saturated_fats: 0.39,
      monounsaturated_fats: 0.39,
      polyunsaturated_fats: 0.78,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 255,
      },
      metric: {
        unit: "g",
        quantity: 255,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zktlapLVNllv",
    name: "Kroger, Sausage, Egg & Cheese Breakfast Sandwich Biscuit by Kroger",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2.08,
      sodium: 692,
      calcium: 77,
      protein: 9.23,
      calories: 292,
      total_fat: 20,
      vitamin_c: 0,
      trans_fats: 1.92,
      cholesterol: 96,
      total_sugars: 3.08,
      vitamin_a_iu: 154,
      carbohydrates: 19.2,
      dietary_fiber: 0.8,
      saturated_fats: 7.69,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 130,
      },
      metric: {
        unit: "g",
        quantity: 130,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZKpaqQ14FmZB",
    name: "Steak and Egg Breakfast Bowl by Hyvee",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.91,
      sodium: 439,
      calcium: 51,
      protein: 7.58,
      calories: 121,
      total_fat: 5.56,
      vitamin_c: 1.8,
      trans_fats: 0,
      cholesterol: 104,
      total_sugars: 1.52,
      vitamin_a_iu: 152,
      carbohydrates: 9.6,
      dietary_fiber: 0.5,
      saturated_fats: 2.02,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 198,
      },
      metric: {
        unit: "g",
        quantity: 198,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zkio09d1JFf9",
    name: "Chocolate Covered Crispy Eggs by Tic Tac",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.67,
      sodium: 83,
      calcium: 150,
      protein: 6.67,
      calories: 567,
      potassium: 360,
      total_fat: 36.7,
      vitamin_d: 0,
      trans_fats: 0,
      cholesterol: 17,
      added_sugars: 36.7,
      total_sugars: 46.7,
      carbohydrates: 53.3,
      dietary_fiber: 3.3,
      saturated_fats: 20,
    },
    serving: {
      common: {
        unit: "piece",
        quantity: 3,
      },
      metric: {
        unit: "g",
        quantity: 30,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZK0AJhPFLWdN",
    name: "Fruit & Veggie Bars, Apple & Greens by Outshine",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 0,
      calcium: 0,
      protein: 0,
      calories: 79,
      total_fat: 0,
      vitamin_c: 27.6,
      vitamin_k: 10.5,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 17.1,
      vitamin_a_iu: 987,
      carbohydrates: 18.4,
      dietary_fiber: 1.3,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 76,
      },
      metric: {
        unit: "g",
        quantity: 76,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZJyv3AoiR6Oi",
    name: "Screamin' Hot Garden Veggie Straws by Sensible Portions",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2.14,
      sodium: 1110,
      calcium: 321,
      protein: 3.57,
      calories: 464,
      potassium: 750,
      total_fat: 25,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 3.57,
      vitamin_d_iu: 0,
      carbohydrates: 60.7,
      dietary_fiber: 1.8,
      saturated_fats: 3.57,
      monounsaturated_fats: 14.3,
      polyunsaturated_fats: 7.14,
    },
    serving: {
      common: {
        unit: "oz",
        quantity: 11,
      },
      metric: {
        unit: "g",
        quantity: 311.8,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZjTYM9KBsb4i",
    name: "Hanover, Veggie Chips, Ranch by Hanover",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 679,
      calcium: 0,
      protein: 3.57,
      calories: 429,
      total_fat: 25,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 3.57,
      vitamin_a_iu: 0,
      carbohydrates: 53.6,
      dietary_fiber: 3.6,
      saturated_fats: 3.57,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 28,
      },
      metric: {
        unit: "g",
        quantity: 28,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zJTMKjrvogFx",
    name: "Shurfine, Small Eggs by Shurfine",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.89,
      sodium: 145,
      calcium: 53,
      protein: 13.2,
      calories: 132,
      total_fat: 9.21,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 368,
      vitamin_a_iu: 526,
      carbohydrates: 0,
      saturated_fats: 2.63,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 38,
      },
      metric: {
        unit: "g",
        quantity: 38,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zJR0YKKLDpnF",
    name: "Bagel Chips, Cream Cheese, Hard Boiled Egg & Dried Fruit by Snack Fresh",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.21,
      sodium: 487,
      calcium: 67,
      protein: 8.4,
      calories: 269,
      potassium: 29,
      total_fat: 12.6,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 164,
      total_sugars: 15.1,
      vitamin_a_iu: 0,
      carbohydrates: 31.9,
      dietary_fiber: 1.7,
      saturated_fats: 6.72,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 119,
      },
      metric: {
        unit: "g",
        quantity: 119,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZJqtuIpC3cwT",
    name: "Veggie Burger by Bubba Burger",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.18,
      sodium: 353,
      calcium: 38,
      protein: 4.71,
      calories: 153,
      potassium: 165,
      total_fat: 4.71,
      vitamin_d: 0,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 1.2,
      total_sugars: 2.35,
      carbohydrates: 24.7,
      dietary_fiber: 3.5,
      saturated_fats: 0,
      monounsaturated_fats: 2.35,
      polyunsaturated_fats: 1.18,
    },
    serving: {
      common: {
        unit: "burger",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 85,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zJlA7G8OEwJt",
    name: "Egg Bites by Vital Farms",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.77,
      sodium: 400,
      calcium: 185,
      protein: 13.8,
      calories: 185,
      potassium: 37,
      total_fat: 13.1,
      trans_fats: 0,
      cholesterol: 281,
      total_sugars: 2.31,
      vitamin_d_iu: 0,
      carbohydrates: 3.85,
      dietary_fiber: 0,
      saturated_fats: 6.15,
    },
    serving: {
      common: {
        unit: "package",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 130,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZJeIOwmbHJFu",
    name: "Broccoli Veggie Puree by Wild Veggie",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.25,
      sodium: 138,
      calcium: 21,
      protein: 1.06,
      calories: 28,
      total_fat: 1.76,
      vitamin_c: 3.2,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 1.41,
      vitamin_a_iu: 176,
      carbohydrates: 2.82,
      dietary_fiber: 1.4,
      saturated_fats: 0.18,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 283.5,
      },
      metric: {
        unit: "g",
        quantity: 283.5,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZjE5JfBo00JB",
    name: "Tuna, Egg, Celery & Onions Blended Together in a Creamy Salad Dressing. by Giant Eagle",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.4,
      sodium: 382,
      calcium: 45,
      protein: 14.6,
      calories: 236,
      potassium: 157,
      total_fat: 18,
      trans_fats: 0,
      cholesterol: 62,
      added_sugars: 1.1,
      total_sugars: 2.25,
      vitamin_d_iu: 0,
      carbohydrates: 3.37,
      dietary_fiber: 0,
      saturated_fats: 2.81,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 0.333,
      },
      metric: {
        unit: "g",
        quantity: 89,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zJ18eamjOY35",
    name: "Marshmallow Bunnies Chicks & Eggs Candy, Marshmallow by Dum Dums",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      sodium: 31,
      protein: 3.12,
      calories: 375,
      total_fat: 0,
      added_sugars: 84.4,
      total_sugars: 84.4,
      carbohydrates: 90.6,
    },
    serving: {
      common: {
        unit: "piece",
        quantity: 4,
      },
      metric: {
        unit: "g",
        quantity: 32,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZIoryfBLbKXI",
    name: "#14 Bootlegger Club®, Unwich by Jimmy John's",
    alternate_names: [],
    description:
      "The #14 Bootlegger Club® from Jimmy John's is a hearty sandwich featuring slow‐roasted roast beef and turkey layered with fresh lettuce, tomato, and a creamy spread of mayo served on French bread. Offered in three formats – Regular (8-inch), Giant (16-inch), and the Unwich® lettuce wrap – it balances a robust meat filling with crisp vegetables to deliver substantial protein and flavor.",
    source: null,
    nutrients: {
      iron: 1.7606,
      zinc: 2.8169,
      water: 60.5634,
      biotin: 4.2254,
      copper: 0.2113,
      iodine: 10.5634,
      lysine: 1.7606,
      niacin: 5.6338,
      serine: 0.993,
      sodium: 830.9859,
      valine: 1.0915,
      alanine: 1.5423,
      calcium: 56.338,
      choline: 38.7324,
      cystine: 0.0986,
      glycine: 1.5423,
      leucine: 1.9718,
      omega_3: 0.0704,
      omega_6: 0.9155,
      omega_9: 1.831,
      proline: 0.993,
      protein: 21.831,
      taurine: 42.2535,
      thiamin: 0.2113,
      xylitol: 0,
      arginine: 1.7394,
      caffeine: 0,
      calories: 232.3944,
      chlorine: 140.8451,
      chromium: 2.1127,
      cysteine: 0.1479,
      selenium: 42.2535,
      sorbitol: 0,
      tyrosine: 0.7465,
      histidine: 0.5493,
      magnesium: 17.6056,
      manganese: 0.3521,
      potassium: 246.4789,
      threonine: 0.8944,
      total_fat: 14.0845,
      vitamin_a: 140.8451,
      vitamin_c: 8.4507,
      vitamin_d: 0,
      vitamin_e: 1.0563,
      vitamin_k: 5.6338,
      folate_dfe: 21.1268,
      isoleucine: 1.0915,
      methionine: 0.4437,
      molybdenum: 21.1268,
      oleic_acid: 3.662,
      phosphorus: 126.7606,
      riboflavin: 0.2817,
      trans_fats: 0.3521,
      tryptophan: 0.2465,
      vitamin_b6: 0.3521,
      capric_acid: 0.0634,
      cholesterol: 77.4648,
      erucic_acid: 0.0282,
      lauric_acid: 0.0634,
      vitamin_b12: 0.8451,
      added_sugars: 0,
      stearic_acid: 0.5634,
      total_sugars: 0.7042,
      aspartic_acid: 2.1831,
      caprylic_acid: 0.0634,
      carbohydrates: 3.5211,
      dietary_fiber: 0.7042,
      ethyl_alcohol: 0,
      glutamic_acid: 3.2746,
      linoleic_acid: 0.7042,
      myristic_acid: 0.4225,
      palmitic_acid: 0.9155,
      phenylalanine: 0.8944,
      soluble_fiber: 0.3521,
      linolenic_acid: 0.007,
      saturated_fats: 2.1127,
      sugar_alcohols: 0,
      eicosenoic_acid: 0.0704,
      insoluble_fiber: 0.3521,
      arachidonic_acid: 0.1408,
      pantothenic_acid: 0.7042,
      other_carbohydrates: 2.1127,
      alpha_linolenic_acid: 0.0704,
      docosahexaenoic_acid: 0.007,
      gamma_linolenic_acid: 0.0704,
      monounsaturated_fats: 6.338,
      polyunsaturated_fats: 5.2817,
      docosapentaenoic_acid: 0.007,
      eicosapentaenoic_acid: 0.007,
      dihomo_gamma_linolenic_acid: 0.0704,
    },
    serving: {
      common: {
        name: "Unwich",
        unit: "lettuce wrap",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 142,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZIIvhe9yzmjQ",
    name: "Kale Veggie Burgers by Dr. Praeger's Sensible Foods",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3.52,
      sodium: 366,
      calcium: 70,
      protein: 14.1,
      calories: 211,
      potassium: 254,
      total_fat: 11.3,
      vitamin_d: 0,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 0,
      total_sugars: 0,
      carbohydrates: 15.5,
      dietary_fiber: 8.5,
      saturated_fats: 1.41,
    },
    serving: {
      common: {
        unit: "burger",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 71,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZiIA4MHent9R",
    name: "Crafty Cooking Kits, Easter Egg Rainbow Sugar Cookie Kit by Brand Castle",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 3.27,
      sodium: 295,
      calcium: 0,
      protein: 4.55,
      calories: 364,
      total_fat: 0,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 36.4,
      vitamin_a_iu: 0,
      carbohydrates: 86.4,
      dietary_fiber: 0,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 22,
      },
      metric: {
        unit: "g",
        quantity: 22,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZHPnbCtP4jBS",
    name: "Jelly Bird Eggs Candy by Black Forest",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 24,
      calcium: 0,
      protein: 0,
      calories: 366,
      total_fat: 0,
      vitamin_a: 0,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 73.2,
      carbohydrates: 90.2,
      dietary_fiber: 0,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "piece",
        quantity: 14,
      },
      metric: {
        unit: "g",
        quantity: 41,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zHeTEGtCZHQF",
    name: "Egg Linguini by Rp's Fresh Pasta",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.85,
      sodium: 624,
      calcium: 24,
      protein: 7.06,
      calories: 259,
      total_fat: 2.35,
      vitamin_a: 0,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 71,
      total_sugars: 0,
      carbohydrates: 55.3,
      dietary_fiber: 3.5,
      saturated_fats: 0.59,
    },
    serving: {
      common: {
        unit: "oz",
        quantity: 3,
      },
      metric: {
        unit: "g",
        quantity: 85,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zhd8vp9mreED",
    name: "Select Sausage Egg Cheese Nuffin by Signature Select",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.44,
      sodium: 698,
      calcium: 65,
      protein: 9.35,
      calories: 266,
      potassium: 137,
      total_fat: 15.8,
      vitamin_d: 0,
      trans_fats: 0,
      cholesterol: 83,
      added_sugars: 1.4,
      total_sugars: 2.16,
      carbohydrates: 20.9,
      dietary_fiber: 0.7,
      saturated_fats: 6.47,
    },
    serving: {
      common: {
        unit: "sandwich",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 139,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zh412m7hTeRW",
    name: "Parmigiano Reggiano Cheese by Murray's",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 643,
      calcium: 1250,
      protein: 32.1,
      calories: 393,
      total_fat: 28.6,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 71,
      total_sugars: 0,
      vitamin_a_iu: 714,
      carbohydrates: 3.57,
      dietary_fiber: 0,
      saturated_fats: 21.4,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 28,
      },
      metric: {
        unit: "g",
        quantity: 28,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zh225rLWvM7D",
    name: "Soda by Reggae Imports Ltd.",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      sodium: 2,
      protein: 0,
      calories: 42,
      total_fat: 0,
      trans_fats: 0,
      added_sugars: 9.6,
      total_sugars: 9.58,
      carbohydrates: 10,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "ml",
        quantity: 240,
      },
      metric: {
        unit: "ml",
        quantity: 240,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zGY2aeDTrTmr",
    name: "100% Liquid Egg Whites by Shoprite",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 174,
      calcium: 0,
      protein: 10.9,
      calories: 54,
      potassium: 174,
      total_fat: 0,
      vitamin_d: 0,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 0,
      total_sugars: 0,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 3,
      },
      metric: {
        unit: "g",
        quantity: 46,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZGlhSHpIAowM",
    name: "Veggie Turkey Meatless Slices by Lightlife Foods",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2.08,
      sodium: 558,
      calcium: 115,
      protein: 26.9,
      calories: 192,
      potassium: 327,
      total_fat: 6.73,
      vitamin_c: 6.9,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 1.92,
      vitamin_a_iu: 0,
      carbohydrates: 7.69,
      dietary_fiber: 3.8,
      saturated_fats: 0.96,
      monounsaturated_fats: 1.92,
      polyunsaturated_fats: 3.85,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 52,
      },
      metric: {
        unit: "g",
        quantity: 52,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZGGYwRGBrYxN",
    name: "Veggi Green Cut Green Beans by Wegmans",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.83,
      zinc: 3.33,
      sodium: 242,
      calcium: 22,
      protein: 0.83,
      calories: 12,
      potassium: 52,
      total_fat: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 0.83,
      vitamin_d_iu: 0,
      carbohydrates: 2.5,
      dietary_fiber: 0.8,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 0.5,
      },
      metric: {
        unit: "g",
        quantity: 120,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zgd1iPfDs0mi",
    name: "Veggie Straw by Pics",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.29,
      sodium: 893,
      calcium: 0,
      protein: 3.57,
      calories: 464,
      potassium: 36,
      total_fat: 25,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 3.57,
      vitamin_a_iu: 0,
      carbohydrates: 57.1,
      dietary_fiber: 0,
      saturated_fats: 1.79,
      monounsaturated_fats: 17.9,
      polyunsaturated_fats: 1.79,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 28,
      },
      metric: {
        unit: "g",
        quantity: 28,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZgA2cbArWlIQ",
    name: "Breakfast Bowl Whole Grain Blend With Dried Fruit by Wild Veggie",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.78,
      sodium: 22,
      calcium: 22,
      protein: 2.72,
      calories: 120,
      total_fat: 0.54,
      vitamin_c: 0,
      trans_fats: 0,
      cholesterol: 0,
      total_sugars: 12.5,
      vitamin_a_iu: 0,
      carbohydrates: 26.6,
      dietary_fiber: 2.7,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "g",
        quantity: 184,
      },
      metric: {
        unit: "g",
        quantity: 184,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zg9oVWcbcowD",
    name: "Wow Protein Donuts by Simply Eggless",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 1.52,
      sodium: 379,
      calcium: 180,
      protein: 16.7,
      calories: 197,
      potassium: 152,
      total_fat: 3.79,
      trans_fats: 0,
      cholesterol: 38,
      added_sugars: 6.1,
      total_sugars: 7.58,
      vitamin_d_iu: 0,
      carbohydrates: 30.3,
      dietary_fiber: 1.5,
      saturated_fats: 0,
      sugar_alcohols: 9,
    },
    serving: {
      common: {
        unit: "donut",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 66,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zg3ar6Mt199W",
    name: "Potato Salad With Cape Free Eggs by Taylor Farms",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.26,
      sodium: 443,
      calcium: 14,
      protein: 2.86,
      calories: 207,
      total_fat: 15.7,
      vitamin_c: 4.3,
      cholesterol: 46,
      total_sugars: 0.71,
      vitamin_a_iu: 71,
      carbohydrates: 12.9,
      dietary_fiber: 1.4,
      saturated_fats: 2.5,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 0.666,
      },
      metric: {
        unit: "g",
        quantity: 140,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zFOX18iImhCo",
    name: "Fresh Eggs by Essential Everyday",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 2.27,
      sodium: 136,
      calcium: 56800,
      protein: 13.6,
      calories: 136,
      potassium: 139,
      total_fat: 9.09,
      trans_fats: 0,
      cholesterol: 375,
      carbohydrates: 0,
      dietary_fiber: 0,
      saturated_fats: 3.41,
    },
    serving: {
      common: {
        unit: "egg",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 44,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_ZfGF3CB8Y3e2",
    name: "Ranch Flavored Veggie Straws by Schnucks",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.36,
      sodium: 893,
      calcium: 71,
      protein: 3.57,
      calories: 500,
      potassium: 500,
      total_fat: 21.4,
      trans_fats: 0,
      cholesterol: 0,
      added_sugars: 3.6,
      total_sugars: 3.57,
      vitamin_d_iu: 0,
      carbohydrates: 60.7,
      dietary_fiber: 3.6,
      saturated_fats: 1.79,
      monounsaturated_fats: 12.5,
      polyunsaturated_fats: 7.14,
    },
    serving: {
      common: {
        unit: "oz",
        quantity: 1,
      },
      metric: {
        unit: "g",
        quantity: 28,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_zFCG5kdgPteJ",
    name: "Dill! Veggie Dip by Marzetti",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0,
      sodium: 600,
      calcium: 0,
      protein: 3.33,
      calories: 367,
      potassium: 0,
      total_fat: 36.7,
      trans_fats: 0,
      cholesterol: 50,
      added_sugars: 3.3,
      total_sugars: 3.33,
      vitamin_d_iu: 0,
      carbohydrates: 6.67,
      dietary_fiber: 0,
      saturated_fats: 10,
    },
    serving: {
      common: {
        unit: "tbsp",
        quantity: 2,
      },
      metric: {
        unit: "g",
        quantity: 30,
      },
    },
    ingredients: null,
  },
  {
    id: "fd_Zf6g1DrjV0EJ",
    name: "Stir-Fry Starters, Vegetables with Noodles, Egg Noodles, Broccoli, Carrots, Celery, Green Peppers, Mushrooms, Onions & Red Peppers by Kroger",
    alternate_names: [],
    description: null,
    source: null,
    nutrients: {
      iron: 0.41,
      sodium: 23,
      calcium: 0,
      protein: 4.6,
      calories: 92,
      total_fat: 0.57,
      vitamin_c: 10.3,
      trans_fats: 0,
      cholesterol: 11,
      total_sugars: 1.15,
      vitamin_a_iu: 230,
      carbohydrates: 16.1,
      dietary_fiber: 1.1,
      saturated_fats: 0,
    },
    serving: {
      common: {
        unit: "cup",
        quantity: 1.25,
      },
      metric: {
        unit: "g",
        quantity: 87,
      },
    },
    ingredients: null,
  },
];
